#include <pebble.h>

// image resources for discharging battery
const int battery_d_res[] = {
  RESOURCE_ID_BATTERY_D_0,
  RESOURCE_ID_BATTERY_D_10,
  RESOURCE_ID_BATTERY_D_20,
  RESOURCE_ID_BATTERY_D_30,
  RESOURCE_ID_BATTERY_D_40,
  RESOURCE_ID_BATTERY_D_50,
  RESOURCE_ID_BATTERY_D_60,
  RESOURCE_ID_BATTERY_D_70,
  RESOURCE_ID_BATTERY_D_80,
  RESOURCE_ID_BATTERY_D_90,
  RESOURCE_ID_BATTERY_D_100,
};

// image resources for scharging battery
const int battery_c_res[] = {
  RESOURCE_ID_BATTERY_C_0,
  RESOURCE_ID_BATTERY_C_10,
  RESOURCE_ID_BATTERY_C_20,
  RESOURCE_ID_BATTERY_C_30,
  RESOURCE_ID_BATTERY_C_40,
  RESOURCE_ID_BATTERY_C_50,
  RESOURCE_ID_BATTERY_C_60,
  RESOURCE_ID_BATTERY_C_70,
  RESOURCE_ID_BATTERY_C_80,
  RESOURCE_ID_BATTERY_C_90,
  RESOURCE_ID_BATTERY_C_100,
};



// flags
#define KEY_SHOW_DIGITAL_TIME 0
#define KEY_SHOW_BLUETOOTH 1
#define KEY_SHOW_BATTERY 2
#define KEY_SHOW_DATE 3
#define KEY_SHOW_DOW 4
#define KEY_SHOW_SECONDS 5
#define KEY_DISABLE_VORTEX_ANIMATION 6