#include <pebble.h>

// image resources for discharging battery
const int battery_d_res[] = {
  RESOURCE_ID_BATTERY_D_0,
  RESOURCE_ID_BATTERY_D_10,
  RESOURCE_ID_BATTERY_D_20,
  RESOURCE_ID_BATTERY_D_30,
  RESOURCE_ID_BATTERY_D_40,
  RESOURCE_ID_BATTERY_D_50,
  RESOURCE_ID_BATTERY_D_60,
  RESOURCE_ID_BATTERY_D_70,
  RESOURCE_ID_BATTERY_D_80,
  RESOURCE_ID_BATTERY_D_90,
  RESOURCE_ID_BATTERY_D_100,
};

// image resources for scharging battery
const int battery_c_res[] = {
  RESOURCE_ID_BATTERY_C_0,
  RESOURCE_ID_BATTERY_C_10,
  RESOURCE_ID_BATTERY_C_20,
  RESOURCE_ID_BATTERY_C_30,
  RESOURCE_ID_BATTERY_C_40,
  RESOURCE_ID_BATTERY_C_50,
  RESOURCE_ID_BATTERY_C_60,
  RESOURCE_ID_BATTERY_C_70,
  RESOURCE_ID_BATTERY_C_80,
  RESOURCE_ID_BATTERY_C_90,
  RESOURCE_ID_BATTERY_C_100,
};

// images used for Aplite sequence animation
const int vortex_aplite_res[] = {  

RESOURCE_ID_VORTEX_APLITE_0,
RESOURCE_ID_VORTEX_APLITE_1,
RESOURCE_ID_VORTEX_APLITE_2,
RESOURCE_ID_VORTEX_APLITE_3,
RESOURCE_ID_VORTEX_APLITE_4,
RESOURCE_ID_VORTEX_APLITE_5,
RESOURCE_ID_VORTEX_APLITE_6,
RESOURCE_ID_VORTEX_APLITE_7,
RESOURCE_ID_VORTEX_APLITE_8,
RESOURCE_ID_VORTEX_APLITE_9,
RESOURCE_ID_VORTEX_APLITE_10,
RESOURCE_ID_VORTEX_APLITE_11,
RESOURCE_ID_VORTEX_APLITE_12,
RESOURCE_ID_VORTEX_APLITE_13,
RESOURCE_ID_VORTEX_APLITE_14,
RESOURCE_ID_VORTEX_APLITE_15,
RESOURCE_ID_VORTEX_APLITE_16,
RESOURCE_ID_VORTEX_APLITE_17,
RESOURCE_ID_VORTEX_APLITE_18,
RESOURCE_ID_VORTEX_APLITE_19,
RESOURCE_ID_VORTEX_APLITE_20,
RESOURCE_ID_VORTEX_APLITE_21,
RESOURCE_ID_VORTEX_APLITE_22,
RESOURCE_ID_VORTEX_APLITE_23,
RESOURCE_ID_VORTEX_APLITE_24,
RESOURCE_ID_VORTEX_APLITE_25,
RESOURCE_ID_VORTEX_APLITE_26,
RESOURCE_ID_VORTEX_APLITE_27,
RESOURCE_ID_VORTEX_APLITE_28,
RESOURCE_ID_VORTEX_APLITE_29,
RESOURCE_ID_VORTEX_APLITE_30,
RESOURCE_ID_VORTEX_APLITE_31,
RESOURCE_ID_VORTEX_APLITE_32,
RESOURCE_ID_VORTEX_APLITE_33,
RESOURCE_ID_VORTEX_APLITE_34,
RESOURCE_ID_VORTEX_APLITE_35,
RESOURCE_ID_VORTEX_APLITE_36,
RESOURCE_ID_VORTEX_APLITE_37

};


// flags
#define KEY_SHOW_DIGITAL_TIME 0
#define KEY_SHOW_BLUETOOTH 1
#define KEY_SHOW_BATTERY 2
#define KEY_SHOW_DATE 3
#define KEY_SHOW_DOW 4
#define KEY_SHOW_SECONDS 5
#define KEY_DISABLE_VORTEX_ANIMATION 6
  
//bluetooth alert types  
#define BLUETOOTH_ALERT_DISABLED 0  
#define BLUETOOTH_ALERT_SILENT 1
#define BLUETOOTH_ALERT_WEAK 2
#define BLUETOOTH_ALERT_NORMAL 3
#define BLUETOOTH_ALERT_STRONG 4
#define BLUETOOTH_ALERT_DOUBLE 5

  
// bluetooth vibe patterns
const VibePattern VIBE_PATTERN_WEAK = {
	.durations = (uint32_t []) {100},
	.num_segments = 1
};

const VibePattern VIBE_PATTERN_NORMAL = {
	.durations = (uint32_t []) {300},
	.num_segments = 1
};

const VibePattern VIBE_PATTERN_STRONG = {
	.durations = (uint32_t []) {500},
	.num_segments = 1
};

const VibePattern VIBE_PATTERN_DOUBLE = {
	.durations = (uint32_t []) {500,100,500},
	.num_segments = 3
};